<a href="https://colab.research.google.com/github/anish00ti/EDA-on-sales/blob/main/Predictive_Ecommerce_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/anish00ti/EDA-on-sales.git

Cloning into 'EDA-on-sales'...
remote: Enumerating objects: 129, done.
remote: Counting objects: 100% (129/129), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 129 (delta 51), reused 44 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (129/129), 5.20 MiB | 11.44 MiB/s, done.
Resolving deltas: 100% (51/51), done.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("EDA-on-sales/data/cleaned/cleaned_sales.csv")

In [4]:
print(df.sample(5))

      Row ID+O6G3A1:R6        order_id  order_date   ship_date  \
1625              7726  CA-2019-113978  2019-09-25  2019-09-29
2176              3464  CA-2019-165470  2019-11-25  2019-11-30
1328              1409  CA-2019-130407  2019-09-02  2019-09-06
1989              5048  CA-2019-158694  2019-11-10  2019-11-13
5259              7963  CA-2020-104864  2020-11-18  2020-11-23

           ship_mode customer_id   customer_name      segment        country  \
1625  Standard Class    TS-21505      Tony Sayre     Consumer  United States
2176  Standard Class    HJ-14875     Heather Jas  Home Office  United States
1328  Standard Class    KD-16270   Karen Daniels     Consumer  United States
1989    Second Class    AI-10855  Arianne Irving     Consumer  United States
5259    Second Class    JS-15685        Jim Sink    Corporate  United States

               city       state region       product_id         category  \
1625      Cleveland        Ohio   East  OFF-ST-10004963  Office Supplies
2176   Jacksonville     Florida  South  OFF-PA-10004675  Office Supplies
1328  New York City    New York   East  FUR-FU-10001967        Furniture
1989    Los Angeles  California   West  OFF-AR-10001227  Office Supplies
5259        Miramar     Florida  South  OFF-BI-10001636  Office Supplies

     sub_category                                       product_name    sales  \
1625      Storage                           Eldon Gobal File Keepers   24.224
2176        Paper  Telephone Message Books with Fax/Mobile Sectio...    5.080
1328  Furnishings                  Telescoping Adjustable Floor Lamp   39.980
1989          Art                                         Newell 338   14.700
5259      Binders        Ibico Plastic and Wire Spiral Binding Combs  138.232

      quantity   profit payment_mode
1625         2  -4.8448        Cards
2176         1   1.6510          COD
1328         2   9.9950          COD
1989         5   3.9690       Online
5259         8 -16.1856          COD

In [5]:
print(f"given data has {df.shape[0]} rows and {df.shape[1]}columns")

given data has 5901 rows and 20columns

In [6]:
df.dtypes

Row ID+O6G3A1:R6      int64
order_id             object
order_date           object
ship_date            object
ship_mode            object
customer_id          object
customer_name        object
segment              object
country              object
city                 object
state                object
region               object
product_id           object
category             object
sub_category         object
product_name         object
sales               float64
quantity              int64
profit              float64
payment_mode         object
dtype: object

In [7]:
df.columns

Index(['Row ID+O6G3A1:R6', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'region', 'product_id', 'category', 'sub_category', 'product_name',
       'sales', 'quantity', 'profit', 'payment_mode'],
      dtype='object')

In [8]:
df['order_date']=pd.to_datetime(df["order_date"], format="mixed" , errors="coerce")
df['ship_date']=pd.to_datetime(df["ship_date"], format="mixed" , errors="coerce")

In [9]:
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month

In [10]:
df['month']=df['month'].map({1:"Jan",2:"Feb" ,3:"Mar",4:"Apr",5:"May",6:"jun",7:"jul",8:"Aug",9:"sep",
10:"Oct",11:"Nov",12:"Dec"})

In [11]:
for col in df.columns:
  if df[col].nunique() < 10:
    df[col]=df[col].astype("category")

In [12]:
print(df.sample(2))

      Row ID+O6G3A1:R6        order_id order_date  ship_date     ship_mode  \
3549              3690  CA-2020-140760 2020-06-02 2020-06-05  Second Class
4999              4586  US-2020-163790 2020-11-02 2020-11-04  Second Class

     customer_id   customer_name      segment        country      city  ...  \
3549    DO-13435    Denny Ordway     Consumer  United States      Mesa  ...
4999    NL-18310  Nancy Lomonaco  Home Office  United States  Danville  ...

           product_id         category sub_category  \
3549  OFF-EN-10001141  Office Supplies    Envelopes
4999  OFF-AR-10003469  Office Supplies          Art

                                           product_name   sales quantity  \
3549  Manila Recycled Extra-Heavyweight Clasp Envelo...  146.92        5
4999                                     Nontoxic Chalk  102.80        5

      profit  payment_mode  year month
3549  15.921        Online  2020   jun
4999   4.224         Cards  2020   Nov

[2 rows x 22 columns]

In [13]:
cols=[""]

In [14]:
df.isnull().sum()

Row ID+O6G3A1:R6    0
order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_id         0
customer_name       0
segment             0
country             0
city                0
state               0
region              0
product_id          0
category            0
sub_category        0
product_name        0
sales               0
quantity            0
profit              0
payment_mode        0
year                0
month               0
dtype: int64

In [34]:
print(f"Number of duplicated rows based on 'order_id': {df.duplicated(subset=['order_id']).sum()}")
display(df[df.duplicated(subset=['order_id'])].head(20))

Number of duplicated rows based on 'order_id': 0

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, region, product_id, category, sub_category, product_name, sales, quantity, profit, payment_mode, year, month]
Index: []

[0 rows x 21 columns]

In [29]:
# Remove duplicated rows based on all columns, keeping the last occurrence
df.drop_duplicates( subset=['order_id'],keep='last', inplace=True)
print(f"DataFrame shape after dropping duplicates: {df.shape}")

DataFrame shape after dropping duplicates: (3003, 21)

In [30]:
print(f"Number of duplicated rows: {df.duplicated().sum()}")
display(df[df.duplicated()].head(10))

Number of duplicated rows: 0

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, region, product_id, category, sub_category, product_name, sales, quantity, profit, payment_mode, year, month]
Index: []

[0 rows x 21 columns]

In [31]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'customer_name', 'segment', 'country', 'city', 'state', 'region',
       'product_id', 'category', 'sub_category', 'product_name', 'sales',
       'quantity', 'profit', 'payment_mode', 'year', 'month'],
      dtype='object')

In [32]:
for col in df.columns:
  unique_value=df[col].nunique()
  print(f"the column ---{col}--- has --{unique_value}--- unique values and is --{df[col].dtypes}")

the column ---order_id--- has --3003--- unique values and is --object
the column ---order_date--- has --642--- unique values and is --datetime64[ns]
the column ---ship_date--- has --690--- unique values and is --datetime64[ns]
the column ---ship_mode--- has --4--- unique values and is --category
the column ---customer_id--- has --773--- unique values and is --object
the column ---customer_name--- has --773--- unique values and is --object
the column ---segment--- has --3--- unique values and is --category
the column ---country--- has --1--- unique values and is --category
the column ---city--- has --452--- unique values and is --object
the column ---state--- has --49--- unique values and is --object
the column ---region--- has --4--- unique values and is --category
the column ---product_id--- has --1446--- unique values and is --object
the column ---category--- has --3--- unique values and is --category
the column ---sub_category--- has --17--- unique values and is --object
the column ---product_name--- has --1432--- unique values and is --object
the column ---sales--- has --2758--- unique values and is --float64
the column ---quantity--- has --14--- unique values and is --int64
the column ---profit--- has --2596--- unique values and is --float64
the column ---payment_mode--- has --3--- unique values and is --category
the column ---year--- has --2--- unique values and is --category
the column ---month--- has --12--- unique values and is --object

In [33]:
df.drop(columns="Row ID+O6G3A1:R6", inplace=True)

KeyError: "['Row ID+O6G3A1:R6'] not found in axis"

In [18]:
def analyze_high_cardinality_object_columns(df):

    print("\n--- Analyzing High Cardinality Object Columns ---")
    for col in df.columns:
        if df[col].dtypes == 'object' and df[col].nunique() >=773 :
            print(f"\nColumn: '{col}' (High Cardinality Object Type)")
            print(df[col].value_counts().head(5))
    print("---------------------------------------------------")

In [19]:

analyze_high_cardinality_object_columns(df)

--- Analyzing High Cardinality Object Columns ---

Column: 'order_id' (High Cardinality Object Type)
order_id
CA-2020-100111    14
CA-2020-157987    12
CA-2019-165330    11
US-2019-108504    11
CA-2019-105732    10
Name: count, dtype: int64

Column: 'customer_id' (High Cardinality Object Type)
customer_id
EP-13915    27
PP-18955    25
EH-13765    25
SV-20365    25
PK-19075    24
Name: count, dtype: int64

Column: 'customer_name' (High Cardinality Object Type)
customer_name
Emily Phan      27
Paul Prost      25
Edward Hooks    25
Seth Vernon     25
Pete Kriz       24
Name: count, dtype: int64

Column: 'product_id' (High Cardinality Object Type)
product_id
TEC-AC-10003832    15
OFF-PA-10001970    13
FUR-TA-10001095    12
FUR-FU-10004864    12
FUR-CH-10003774    11
Name: count, dtype: int64

Column: 'product_name' (High Cardinality Object Type)
product_name
Easy-staple paper          27
Staples                    24
Staple envelope            22
Staples in misc. colors    13
Staple remover             12
Name: count, dtype: int64
---------------------------------------------------

In [20]:
def columns(df):
  for col in df.columns:
    number_of_unique_value=df[col].nunique()
    print(f"we have coumn name  [-{col}-] is of [-{df[col].dtype}-] and has unique value[-{number_of_unique_value}-]")

In [21]:
columns(df)

we have coumn name  [-order_id-] is of [-object-] and has unique value[-3003-]
we have coumn name  [-order_date-] is of [-datetime64[ns]-] and has unique value[-643-]
we have coumn name  [-ship_date-] is of [-datetime64[ns]-] and has unique value[-690-]
we have coumn name  [-ship_mode-] is of [-category-] and has unique value[-4-]
we have coumn name  [-customer_id-] is of [-object-] and has unique value[-773-]
we have coumn name  [-customer_name-] is of [-object-] and has unique value[-773-]
we have coumn name  [-segment-] is of [-category-] and has unique value[-3-]
we have coumn name  [-country-] is of [-category-] and has unique value[-1-]
we have coumn name  [-city-] is of [-object-] and has unique value[-452-]
we have coumn name  [-state-] is of [-object-] and has unique value[-49-]
we have coumn name  [-region-] is of [-category-] and has unique value[-4-]
we have coumn name  [-product_id-] is of [-object-] and has unique value[-1755-]
we have coumn name  [-category-] is of [-category-] and has unique value[-3-]
we have coumn name  [-sub_category-] is of [-object-] and has unique value[-17-]
we have coumn name  [-product_name-] is of [-object-] and has unique value[-1742-]
we have coumn name  [-sales-] is of [-float64-] and has unique value[-5109-]
we have coumn name  [-quantity-] is of [-int64-] and has unique value[-14-]
we have coumn name  [-profit-] is of [-float64-] and has unique value[-4739-]
we have coumn name  [-payment_mode-] is of [-category-] and has unique value[-3-]
we have coumn name  [-year-] is of [-category-] and has unique value[-2-]
we have coumn name  [-month-] is of [-object-] and has unique value[-12-]

## Column Categorization

**Numerical Columns**
sales
quantity
profit

**Time Columns**
order_date
ship_date
month
year

**Customer Columns**
customer_id
customer_name
segment

**Product Columns**
category
sub_category
product_name

**Geographic Columns**
city
state
region

**Shipping Columns**
ship_mode

In [ ]:
Business Questions
what is the total average total  sales , total quantity sold , total profit
what is the average delivery time
which customer segment we earn more revenue and which customer segment we sold more qty and profit generated
whuch category is most solt item  , which category generate more profit  ,
which payment mode is widely used and which  mode is increasing over time and which is decreased
which shipping mode is increasing and which is decreasing
which city state and region contribute more revenue over time
on which month have highest revenue
sales over year is it increasing from previous year or not
which category is most sold quantity

**date validation**

In [35]:
df[['order_date','ship_date']].describe()

                          order_date                      ship_date
count                           3003                           3003
mean   2020-02-29 22:25:32.067932160  2020-03-04 20:52:30.449550336
min              2019-01-02 00:00:00            2019-01-05 00:00:00
25%              2019-09-13 12:00:00            2019-09-18 00:00:00
50%              2020-03-19 00:00:00            2020-03-23 00:00:00
75%              2020-09-14 00:00:00            2020-09-17 00:00:00
max              2020-12-31 00:00:00            2021-01-05 00:00:00

The date validation shows that order_date ranges from 2019-01-02 to 2020-12-31, and ship_date ranges from 2019-01-05 to 2021-01-05. On average, items are shipped about 3 to 4 days after the order is placed.

**Stage 3: Univariate Analysis**