<a href="https://colab.research.google.com/github/anish00ti/EDA-on-sales/blob/main/Predictive_Ecommerce_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/anish00ti/EDA-on-sales.git

Cloning into 'EDA-on-sales'...
remote: Enumerating objects: 126, done.
remote: Counting objects: 100% (126/126), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 126 (delta 49), reused 44 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (126/126), 5.20 MiB | 13.79 MiB/s, done.
Resolving deltas: 100% (49/49), done.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("EDA-on-sales/data/cleaned/cleaned_sales.csv")

In [4]:
print(df.sample(5))

      Row ID+O6G3A1:R6        order_id  order_date   ship_date  \
444               7781  CA-2019-139381  2019-04-18  2019-04-22
2299              5777  CA-2019-105277  2019-12-04  2019-12-08
2145              8080  US-2019-164945  2019-11-22  2019-11-27
1223              6870  US-2019-126452  2019-08-21  2019-08-28
2394              7054  CA-2019-165330  2019-12-11  2019-12-11

           ship_mode customer_id    customer_name      segment        country  \
444   Standard Class    RF-19840  Roy Französisch     Consumer  United States
2299  Standard Class    LM-17065  Liz MacKendrick     Consumer  United States
2145  Standard Class    CA-12055  Cathy Armstrong  Home Office  United States
1223  Standard Class    SC-20230       Scot Coram    Corporate  United States
2394        Same Day    WB-21850    William Brown     Consumer  United States

               city       state region       product_id         category  \
444      Chesapeake    Virginia  South  TEC-PH-10004924       Technology
2299         Auburn    New York   East  OFF-BI-10000301  Office Supplies
2145  New York City    New York   East  OFF-BI-10001524  Office Supplies
1223    Los Angeles  California   West  OFF-PA-10003848  Office Supplies
2394        Anaheim  California   West  TEC-AC-10000057       Technology

     sub_category                                       product_name    sales  \
444        Phones  SKILCRAFT Telephone Shoulder Rest, 2" x 6.5" x...   29.560
2299      Binders                             GBC Instant Report Kit   15.528
2145      Binders  GBC Premium Transparent Covers with Diagonal L...  134.272
1223        Paper                                         Xerox 1997   12.960
2394  Accessories          Microsoft Natural Ergonomic Keyboard 4000  119.960

      quantity   profit payment_mode
444          4   7.9812          COD
2299         3   5.8230       Online
2145         8  46.9952       Online
1223         2   6.2208        Cards
2394         4  25.1916          COD

In [5]:
print(f"given data has {df.shape[0]} rows and {df.shape[1]}columns")

given data has 5901 rows and 20columns

In [21]:
df.dtypes

Row ID+O6G3A1:R6             int64
order_id                    object
order_date          datetime64[ns]
ship_date           datetime64[ns]
ship_mode                 category
customer_id                 object
customer_name               object
segment                   category
country                   category
city                        object
state                       object
region                    category
product_id                  object
category                  category
sub_category                object
product_name                object
sales                      float64
quantity                     int64
profit                     float64
payment_mode              category
year                         int32
month                     category
dtype: object

In [7]:
df.columns

Index(['Row ID+O6G3A1:R6', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'region', 'product_id', 'category', 'sub_category', 'product_name',
       'sales', 'quantity', 'profit', 'payment_mode'],
      dtype='object')

In [14]:
df['order_date']=pd.to_datetime(df["order_date"], format="mixed" , errors="coerce")
df['ship_date']=pd.to_datetime(df["ship_date"], format="mixed" , errors="coerce")

In [32]:
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month

In [33]:
df['month']=df['month'].map({1:"Jan",2:"Feb" ,3:"Mar",4:"Apr",5:"May",6:"jun",7:"jul",8:"Aug",9:"sep",
10:"Oct",11:"Nov",12:"Dec"})

In [34]:
for col in df.columns:
  if df[col].nunique() < 10:
    df[col]=df[col].astype("category")

In [37]:
print(df.sample(2))

      Row ID+O6G3A1:R6        order_id order_date  ship_date       ship_mode  \
4636              4564  CA-2020-129490 2020-09-26 2020-09-30  Standard Class
1987              5046  CA-2019-158694 2019-11-10 2019-11-13    Second Class

     customer_id   customer_name      segment        country         city  \
4636    SJ-20125   Sanjit Jacobs  Home Office  United States      Miramar
1987    AI-10855  Arianne Irving     Consumer  United States  Los Angeles

      ...       product_id         category sub_category  \
4636  ...  FUR-CH-10003298        Furniture       Chairs
1987  ...  OFF-ST-10001496  Office Supplies      Storage

                                           product_name    sales quantity  \
4636  Office Star - Contemporary Task Swivel chair w...  446.136        4
1987                   Standard Rollaway File with Lock  720.760        4

        profit  payment_mode  year month
4636  -57.6312        Online  2020   sep
1987  187.3976        Online  2019   Nov

[2 rows x 22 columns]

In [ ]:
cols=[""]

In [36]:
df.isnull().sum()

Row ID+O6G3A1:R6    0
order_id            0
order_date          0
ship_date           0
ship_mode           0
customer_id         0
customer_name       0
segment             0
country             0
city                0
state               0
region              0
product_id          0
category            0
sub_category        0
product_name        0
sales               0
quantity            0
profit              0
payment_mode        0
year                0
month               0
dtype: int64

In [47]:
df.columns

Index(['Row ID+O6G3A1:R6', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'region', 'product_id', 'category', 'sub_category', 'product_name',
       'sales', 'quantity', 'profit', 'payment_mode', 'year', 'month'],
      dtype='object')

In [87]:
for col in df.columns:
  unique_value=df[col].nunique()
  print(f"the column ---{col}--- has --{unique_value}--- unique values and is --{df[col].dtypes}")

the column ---order_id--- has --3003--- unique values and is --object
the column ---order_date--- has --643--- unique values and is --datetime64[ns]
the column ---ship_date--- has --690--- unique values and is --datetime64[ns]
the column ---ship_mode--- has --4--- unique values and is --category
the column ---customer_id--- has --773--- unique values and is --object
the column ---customer_name--- has --773--- unique values and is --object
the column ---segment--- has --3--- unique values and is --category
the column ---country--- has --1--- unique values and is --category
the column ---city--- has --452--- unique values and is --object
the column ---state--- has --49--- unique values and is --object
the column ---region--- has --4--- unique values and is --category
the column ---product_id--- has --1755--- unique values and is --object
the column ---category--- has --3--- unique values and is --category
the column ---sub_category--- has --17--- unique values and is --object
the column ---product_name--- has --1742--- unique values and is --object
the column ---sales--- has --5109--- unique values and is --float64
the column ---quantity--- has --14--- unique values and is --int64
the column ---profit--- has --4739--- unique values and is --float64
the column ---payment_mode--- has --3--- unique values and is --category
the column ---year--- has --2--- unique values and is --category
the column ---month--- has --12--- unique values and is --object

In [58]:
df.drop(columns="Row ID+O6G3A1:R6", inplace=True)

In [88]:
def analyze_high_cardinality_object_columns(df):

    print("\n--- Analyzing High Cardinality Object Columns ---")
    for col in df.columns:
        if df[col].dtypes == 'object' and df[col].nunique() >=773 :
            print(f"\nColumn: '{col}' (High Cardinality Object Type)")
            print(df[col].value_counts().head(5))
    print("---------------------------------------------------")

In [89]:

analyze_high_cardinality_object_columns(df)

--- Analyzing High Cardinality Object Columns ---

Column: 'order_id' (High Cardinality Object Type)
order_id
CA-2020-100111    14
CA-2020-157987    12
CA-2019-165330    11
US-2019-108504    11
CA-2019-105732    10
Name: count, dtype: int64

Column: 'customer_id' (High Cardinality Object Type)
customer_id
EP-13915    27
PP-18955    25
EH-13765    25
SV-20365    25
PK-19075    24
Name: count, dtype: int64

Column: 'customer_name' (High Cardinality Object Type)
customer_name
Emily Phan      27
Paul Prost      25
Edward Hooks    25
Seth Vernon     25
Pete Kriz       24
Name: count, dtype: int64

Column: 'product_id' (High Cardinality Object Type)
product_id
TEC-AC-10003832    15
OFF-PA-10001970    13
FUR-TA-10001095    12
FUR-FU-10004864    12
FUR-CH-10003774    11
Name: count, dtype: int64

Column: 'product_name' (High Cardinality Object Type)
product_name
Easy-staple paper          27
Staples                    24
Staple envelope            22
Staples in misc. colors    13
Staple remover             12
Name: count, dtype: int64
---------------------------------------------------

In [92]:
def columns(df):
  for col in df.columns:
    number_of_unique_value=df[col].nunique()
    print(f"we have coumn name  [-{col}-] is of [-{df[col].dtype}-] and has unique value[-{number_of_unique_value}-]")

In [93]:
columns(df)

we have coumn name  [-order_id-] is of [-object-] and has unique value[-3003-]
we have coumn name  [-order_date-] is of [-datetime64[ns]-] and has unique value[-643-]
we have coumn name  [-ship_date-] is of [-datetime64[ns]-] and has unique value[-690-]
we have coumn name  [-ship_mode-] is of [-category-] and has unique value[-4-]
we have coumn name  [-customer_id-] is of [-object-] and has unique value[-773-]
we have coumn name  [-customer_name-] is of [-object-] and has unique value[-773-]
we have coumn name  [-segment-] is of [-category-] and has unique value[-3-]
we have coumn name  [-country-] is of [-category-] and has unique value[-1-]
we have coumn name  [-city-] is of [-object-] and has unique value[-452-]
we have coumn name  [-state-] is of [-object-] and has unique value[-49-]
we have coumn name  [-region-] is of [-category-] and has unique value[-4-]
we have coumn name  [-product_id-] is of [-object-] and has unique value[-1755-]
we have coumn name  [-category-] is of [-category-] and has unique value[-3-]
we have coumn name  [-sub_category-] is of [-object-] and has unique value[-17-]
we have coumn name  [-product_name-] is of [-object-] and has unique value[-1742-]
we have coumn name  [-sales-] is of [-float64-] and has unique value[-5109-]
we have coumn name  [-quantity-] is of [-int64-] and has unique value[-14-]
we have coumn name  [-profit-] is of [-float64-] and has unique value[-4739-]
we have coumn name  [-payment_mode-] is of [-category-] and has unique value[-3-]
we have coumn name  [-year-] is of [-category-] and has unique value[-2-]
we have coumn name  [-month-] is of [-object-] and has unique value[-12-]